version: '3.5'

services:

  db:
    image: mongo:latest
    ports:
      - '27017:27017'

  parser:
    build: ./parser
    depends_on:
      - db

  api:
    build: ./api
    depends_on:
      - db
      - parser
    ports:
      - '5000:5000'
